export enum NotificacaoTipoEnum {
    MENSAGEM_COMUM = 'MENSAGEM_COMUM',
    MENSAGEM_PRIORITARIA = 'MENSAGEM_PRIORITARIA',
    MENSAGEM_PROGRAMADA = 'MENSAGEM_PROGRAMADA',
    CARGA = 'CARGA',
    NOTIFICACAO_APROVACAO_SOLICITACAO = 'NOTIFICACAO_APROVACAO_SOLICITACAO',
 }