
export enum StatusPedido{
    CRIADO='CRIADO',
    PENDENTE_ESTOQUE='PENDENTE_ESTOQUE',
    PENDENTE_PAGAMENTO='PENDENTE_PAGAMENTO',
    PAGO='PAGO',
    FATURADO='FATURADO',
    ENVIADO='ENVIADO',
    ENTREGUE='ENTREGUE',
    FINALIZADO='FINALIZADO',
    CANCELAMENTO_SOLICITADO='CANCELAMENTO_SOLICITADO',
    CANCELADO='CANCELADO'
}